### ISSUE TITLE
Allow argument type: List

### ISSUE THREAD

**Issue by nocotan** [CompML/PRTS#38]
## Summary
Currenty, ts_precision/ts_metric function only allow ```np.ndarray``` as the real/pred argument.
However, the scikit-learn interface allows list type too.

Then, why don't you make it possible to accept list type?

## Goal

Accept list type.

## Todo
- [x] rewrite the class: TimeSeriesPrecision
- [x] rewrite the class: TimeSeriesRecall

## Deadline
yyyy / mm / dd  

## Parent issue
If the parent issue exists, post a link here.  

## References
If there are any reference links, they are described here.  

## Notes
Other comments.

**Comment by ryoherisson** [comment]
Done
